apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: grafana-operator.fling.vsphere.vmware.com
spec:
  categories:
  - Visualization
  - Observability
  displayName: grafana-operator
  iconSVGBase64: none
  longDescription: The Grafana Operator is a Kubernetes operator built to help you manage your Grafana instances and its resources in and outside of Kubernetes. Whether you’re running one Grafana instance or many, the Grafana Operator simplifies the processes of installing, configuring, and maintaining Grafana and its resources. Additionally, it's perfect for those who prefer to manage resources using infrastructure as code or using GitOps workflows through tools like ArgoCD and Flux CD.
  maintainers:
  - name: supervisor-services-labs.pdl@broadcom.com
  providerName: VMware
  shortDescription: The Grafana Operator is a Kubernetes operator built to help you manage your Grafana instances and its resources in and outside of Kubernetes.
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: grafana-operator.fling.vsphere.vmware.com.5.9.0
spec:
  refName: grafana-operator.fling.vsphere.vmware.com
  releasedAt: "2024-05-13T23:41:36Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/vsphere-labs/grafana-operator@sha256:a74b04131c238e08ad4330bc04ac6d82ac00b38f90da48119fc2d95b5458f413
      template:
      - ytt:
          paths:
          - ./config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      default: null
      nullable: true
  version: 5.9.0
